version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: rafid-elahi
      POSTGRES_PASSWORD: 142536
      POSTGRES_DB: teebay
    ports:
      - "5432:5432"
